import { FC, ReactNode } from 'react'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

type Props = { children: ReactNode }

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
