const STATUS_SUCCESS = 200
const STATUS_BAD_REQUEST = 400
const STATUS_NOT_FOUND = 404

export enum StatusCode {
  NOT_FOUND = STATUS_NOT_FOUND,
  SUCCESS = STATUS_SUCCESS,
  BAD_REQUEST = STATUS_BAD_REQUEST,
}
